name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          
      - name: Publish to GitHub Packages
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          
      - name: Create JitPack Release
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const tag = context.ref.replace('refs/tags/', '');
            
            // Create a release to trigger JitPack
            await github.rest.repos.createRelease({
              owner,
              repo,
              tag_name: tag,
              name: `Release ${tag}`,
              body: `Release ${tag} for JitPack`
            }); 